backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

media_folder: static/uploads
public_folder: /uploads

collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'static/posts'
      create: true
      fields:
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime', date_format: 'MM-DD-YYYY', time_format: 'HH:mm' }
          - { label: 'Overview', name: 'overview', widget: 'string' }
          - { label: 'Tags', name: 'tags', widget: 'list' }
          - { label: 'Thumbnail', name: 'thumb', widget: image }
          - { label: 'Image', name: 'img', widget: 'image' }
          - { label: 'intro', name: 'intro', widget: 'markdown' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    - name: 'projects'
      label: 'Projects'
      folder: 'static/projects'
      create: true
      fields:
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime', date_format: 'MM-DD-YYYY', time_format: 'HH:mm' }
          - { label: 'Overview', name: 'overview', widget: 'string' }
          - { label: 'Tags', name: 'tags', widget: 'list' }
          - { label: 'Tools', name: 'tools', widget: 'list' }
          - { label: 'Thumbnail', name: 'thumb', widget: image }
          - { label: 'Image', name: 'img', widget: 'image' }
          - { label: 'link', name: 'link', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
